# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cmdui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cmdform(object):
    def setupUi(self, cmdform):
        cmdform.setObjectName("cmdform")
        cmdform.resize(641, 334)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("scientist.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        cmdform.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(cmdform)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tbOutput = QtWidgets.QTextBrowser(cmdform)
        self.tbOutput.setObjectName("tbOutput")
        self.verticalLayout.addWidget(self.tbOutput)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.qlInput = QtWidgets.QLineEdit(cmdform)
        self.qlInput.setObjectName("qlInput")
        self.horizontalLayout.addWidget(self.qlInput)
        self.pbSend = QtWidgets.QPushButton(cmdform)
        self.pbSend.setObjectName("pbSend")
        self.horizontalLayout.addWidget(self.pbSend)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(cmdform)
        QtCore.QMetaObject.connectSlotsByName(cmdform)

    def retranslateUi(self, cmdform):
        _translate = QtCore.QCoreApplication.translate
        cmdform.setWindowTitle(_translate("cmdform", " "))
        self.tbOutput.setHtml(_translate("cmdform", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pbSend.setText(_translate("cmdform", "send"))
