# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filemanagerui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FileManager(object):
    def setupUi(self, FileManager):
        FileManager.setObjectName("FileManager")
        FileManager.resize(487, 537)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("scientist.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FileManager.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(FileManager)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leInputPath = QtWidgets.QLineEdit(self.centralwidget)
        self.leInputPath.setObjectName("leInputPath")
        self.horizontalLayout.addWidget(self.leInputPath)
        self.cbDriver = QtWidgets.QComboBox(self.centralwidget)
        self.cbDriver.setObjectName("cbDriver")
        self.horizontalLayout.addWidget(self.cbDriver)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.twList = QtWidgets.QTableWidget(self.centralwidget)
        self.twList.setFocusPolicy(QtCore.Qt.NoFocus)
        self.twList.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.twList.setStyleSheet("selection-background-color: rgb(0, 170, 255);")
        self.twList.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.twList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.twList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.twList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.twList.setShowGrid(False)
        self.twList.setGridStyle(QtCore.Qt.CustomDashLine)
        self.twList.setRowCount(0)
        self.twList.setObjectName("twList")
        self.twList.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.twList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.twList.setHorizontalHeaderItem(3, item)
        self.twList.horizontalHeader().setHighlightSections(False)
        self.twList.horizontalHeader().setMinimumSectionSize(20)
        self.twList.horizontalHeader().setStretchLastSection(True)
        self.twList.verticalHeader().setVisible(False)
        self.twList.verticalHeader().setDefaultSectionSize(20)
        self.twList.verticalHeader().setMinimumSectionSize(20)
        self.twList.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.twList)
        FileManager.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FileManager)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 487, 23))
        self.menubar.setObjectName("menubar")
        FileManager.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FileManager)
        self.statusbar.setObjectName("statusbar")
        FileManager.setStatusBar(self.statusbar)

        self.retranslateUi(FileManager)
        QtCore.QMetaObject.connectSlotsByName(FileManager)

    def retranslateUi(self, FileManager):
        _translate = QtCore.QCoreApplication.translate
        FileManager.setWindowTitle(_translate("FileManager", "MainWindow"))
        item = self.twList.horizontalHeaderItem(0)
        item.setText(_translate("FileManager", "Name"))
        item = self.twList.horizontalHeaderItem(1)
        item.setText(_translate("FileManager", "Date Modified"))
        item = self.twList.horizontalHeaderItem(2)
        item.setText(_translate("FileManager", "Type"))
        item = self.twList.horizontalHeaderItem(3)
        item.setText(_translate("FileManager", "Size"))
